# Generated by Django 4.1.7 on 2023-03-07 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
